version: "3.8"

services:
  web:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_PROJECT=AI-Scrape
      - OLLAMA_HOST=host.docker.internal
      - OLLAMA_PORT=11434

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - 11434:11434
  #   volumes:
  #     - ./ollama/ollama:/root/.ollama
