version: "3.8"

services:
  app:
    container_name: app
    build:
      context: ./app/
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=true
      - LANGCHAIN_PROJECT=company-research

  redis:
    container_name: redis
    image: "redis:alpine"
    ports:
      - "6379:6379"

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ./ollama/ollama:/root/.ollama
